export enum AppointmentStatusValue {
  SCHEDULED = 'SCHEDULED',
  CONFIRMATION_PENDING = 'CONFIRMATION_PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  RESCHEDULE_REQUESTED = 'RESCHEDULE_REQUESTED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum AppointmentSourceValue {
  RECURRING = 'RECURRING',
  RESCHEDULE = 'RESCHEDULE',
}

export enum MessageKindValue {
  CONFIRMATION = 'CONFIRMATION',
  RESCHEDULE_OPTIONS = 'RESCHEDULE_OPTIONS',
}
